#macro ATTACK_CATEGORY_GROUND 0
#macro ATTACK_CATEGORY_AIR 1
#macro ATTACK_CATEGORY_GROUND_OR_AIR 2

#macro WINDOW_TYPE_PRATFALL 7
#macro WINDOW_TYPE_SKIP_ON_GROUND 8
#macro WINDOW_TYPE_LOOP 9
#macro WINDOW_TYPE_SKIP_IN_AIR 10

#macro WINDOW_SPEED_TYPE_ADD 0
#macro WINDOW_SPEED_TYPE_LOCK 1
#macro WINDOW_SPEED_TYPE_SET_ONCE 2

#macro WINDOW_INVINCIBILITY_TYPE_ALL 1
#macro WINDOW_INVINCIBILITY_TYPE_PROJECTILES 2

#macro WINDOW_CANCEL_TYPE_ON_ATTACK 1
#macro WINDOW_CANCEL_TYPE_ON_SPECIAL 2

#macro HITBOX_TYPE_MELEE 1
#macro HITBOX_TYPE_RANGED 2

#macro HITBOX_SHAPE_CIRCLE 0
#macro HITBOX_SHAPE_RECT 1
#macro HITBOX_SHAPE_ROUND_RECT 2

#macro HITBOX_EFFECT_BURN 1
#macro HITBOX_EFFECT_BURN_CONSUME 2
#macro HITBOX_EFFECT_BURN_STUN 3
#macro HITBOX_EFFECT_WRAP 4
#macro HITBOX_EFFECT_FREEZE 5
#macro HITBOX_EFFECT_MARK 6
#macro HITBOX_EFFECT_AUTO_WRAP 8
#macro HITBOX_EFFECT_POLITE 9
#macro HITBOX_EFFECT_POISON 10
#macro HITBOX_EFFECT_PLASMA_STUN 11
#macro HITBOX_EFFECT_CROUCH_ARMORED 12

#macro HITBOX_ANGLE_FLIPPER_NORMAL 0
#macro HITBOX_ANGLE_FLIPPER_AWAY_FROM_ATTACKER 1
#macro HITBOX_ANGLE_FLIPPER_TOWARD_ATTACKER 2
#macro HITBOX_ANGLE_FLIPPER_HORIZONTAL_AWAY_FROM_HITBOX 3
#macro HITBOX_ANGLE_FLIPPER_HORIZONTAL_TOWARD_HITBOX 4
#macro HITBOX_ANGLE_FLIPPER_HORIZONTAL_REVERSED 5
#macro HITBOX_ANGLE_FLIPPER_HORIZONTAL_AWAY_FROM_ATTACKER 6
#macro HITBOX_ANGLE_FLIPPER_HORIZONTAL_TOWARD_ATTACKER 7
#macro HITBOX_ANGLE_FLIPPER_AWAY_FROM_HITBOX 8
#macro HITBOX_ANGLE_FLIPPER_TOWARD_HITBOX 9
#macro HITBOX_ANGLE_FLIPPER_ATTACKERS_MOVEMENT 10

#macro HITBOX_GROUNDEDNESS_GROUND_ONLY 1
#macro HITBOX_GROUNDEDNESS_AIR_ONLY 2

#macro HITBOX_TECHABLE_YES 0
#macro HITBOX_TECHABLE_NO_TECH 1
#macro HITBOX_TECHABLE_GOES_THROUGH_PLATFORMS 2
#macro HITBOX_TECHABLE_NO_TECH_OR_BOUNCE 3

#macro HITBOX_FORCE_FLINCH_NO 0
#macro HITBOX_FORCE_FLINCH_GROUNDED 1
#macro HITBOX_FORCE_FLINCH_NEVER 2
#macro HITBOX_FORCE_FLINCH_CROUCHING 3

#macro HITBOX_THROWS_ROCK_BREAKS 0
#macro HITBOX_THROWS_ROCK_THROWS 1
#macro HITBOX_THROWS_ROCK_IGNORES 2

#macro HITBOX_PROJECTILE_TERRAIN_STOP 0
#macro HITBOX_PROJECTILE_TERRAIN_IGNORE 1
#macro HITBOX_PROJECTILE_TERRAIN_BOUNCE 2