
#macro HG_VISUAL_EFFECT_NONE 1
#macro HG_VISUAL_EFFECT_BASIC_SMALL 301
#macro HG_VISUAL_EFFECT_BASIC_SMALL_SPIN 302
#macro HG_VISUAL_EFFECT_BASIC_SMALL_DIRECTIONAL 303
#macro HG_VISUAL_EFFECT_BASIC_LARGE 304
#macro HG_VISUAL_EFFECT_BASIC_SWEETSPOT 305
#macro HG_VISUAL_EFFECT_SWEETSPOT_SMALL 19

#macro HG_VISUAL_EFFECT_FIRE_SMALL 3
#macro HG_VISUAL_EFFECT_FIRE_DIRECTIONAL 4
#macro HG_VISUAL_EFFECT_FIRE_LARGE 138

#macro HG_VISUAL_EFFECT_PLASMA_FSPECIAL_X 121
#macro HG_VISUAL_EFFECT_PLASMA_FSPECIAL_X_HIT 123
#macro HG_VISUAL_EFFECT_PLASMA_HIT_SMALL 124
#macro HG_VISUAL_EFFECT_PLASMA_HIT_SMALL_X 129
#macro HG_VISUAL_EFFECT_PLASMA_HIT_SMALL_CROSS 128
#macro HG_VISUAL_EFFECT_PLASMA_HIT_LARGE_X 130
#macro HG_VISUAL_EFFECT_PLASMA_ORB_BREAK 256
#macro HG_VISUAL_EFFECT_TIPPER_HIT_SMALL_X 125
#macro HG_VISUAL_EFFECT_TIPPER_HIT_SMALL_CROSS 125
#macro HG_VISUAL_EFFECT_TIPPER_HIT_LARGE 127

#macro HG_VISUAL_EFFECT_WIND_SMALL 194
#macro HG_VISUAL_EFFECT_WIND_LARGE 156
#macro HG_VISUAL_EFFECT_WIND_EXTRA_LARGE 196
#macro HG_VISUAL_EFFECT_FEATHERS_SIDE_SMALL 11
#macro HG_VISUAL_EFFECT_FEATHERS_UP_SMALL 12
#macro HG_VISUAL_EFFECT_FEATHERS_SIDE_LARGE 146
#macro HG_VISUAL_EFFECT_FEATHERS_UP_LARGE 147

#macro HG_VISUAL_EFFECT_SEED_BREAK_1 15
#macro HG_VISUAL_EFFECT_SEED_BREAK_2 16
#macro HG_VISUAL_EFFECT_LEAF_SMALL 17
#macro HG_VISUAL_EFFECT_LEAF_TINY 18
#macro HG_VISUAL_EFFECT_LEAF_LARGE 198
#macro HG_VISUAL_EFFECT_LEAF_EXTRA_LARGE 159

#macro HG_VISUAL_EFFECT_FLOWER_LARGE 131
#macro HG_VISUAL_EFFECT_FLOWER_SMALL 132
#macro HG_VISUAL_EFFECT_FLOWER_SWEETSPOT 133
#macro HG_VISUAL_EFFECT_WOOD_LARGE 134
#macro HG_VISUAL_EFFECT_WOOD_SMALL 135
#macro HG_VISUAL_EFFECT_WOOD_EXTRA_LARGE 162

#macro HG_VISUAL_EFFECT_FIRE_WHIP_LARGE 204
#macro HG_VISUAL_EFFECT_METAL_BREAK 136
#macro HG_VISUAL_EFFECT_MOLTEN_METAL_BREAK 137

#macro HG_VISUAL_EFFECT_LIGHTNING_SMALL 20
#macro HG_VISUAL_EFFECT_LIGHTNING_MEDIUM 21
#macro HG_VISUAL_EFFECT_LIGHTNING_DIRECTIONAL 22
#macro HG_VISUAL_EFFECT_LIGHTNING_LARGE 197
#macro HG_VISUAL_EFFECT_LIGHTNING_EXTRA_LARGE 157

#macro HG_VISUAL_EFFECT_ROCK_LARGE 192
#macro HG_VISUAL_EFFECT_ROCK_SMALL 193
#macro HG_VISUAL_EFFECT_ROCK_EXTRA_LARGE 155
#macro HG_VISUAL_EFFECT_SMOKE_LARGE 13
#macro HG_VISUAL_EFFECT_SMOKE_SMALL 14

#macro HG_VISUAL_EFFECT_DARK_WATER_SMALL 5
#macro HG_VISUAL_EFFECT_LIGHT_WATER_SMALL 6
#macro HG_VISUAL_EFFECT_LIGHT_AND_DARK_WATER_SMALL 7
#macro HG_VISUAL_EFFECT_DARK_WATER_DIRECTIONAL 8
#macro HG_VISUAL_EFFECT_LIGHT_WATER_DIRECTIONAL 9 
#macro HG_VISUAL_EFFECT_LIGHT_AND_DARK_WATER_DIRECTIONAL 10
#macro HG_VISUAL_EFFECT_DARK_WATER_MEDIUM 149
#macro HG_VISUAL_EFFECT_LIGHT_WATER_MEDIUM 150
#macro HG_VISUAL_EFFECT_WATER_LARGE 195
#macro HG_VISUAL_EFFECT_WATER_EXTRA_LARGE 161

#macro HG_VISUAL_EFFECT_ICE_LARGE 199
#macro HG_VISUAL_EFFECT_ICE_EXTRA_LARGE 158
#macro HG_VISUAL_EFFECT_ICE_SHARD_LONG 25
#macro HG_VISUAL_EFFECT_ICE_SHARD_MEDIUM 26
#macro HG_VISUAL_EFFECT_ICE_FLASH_SMALL 27
#macro HG_VISUAL_EFFECT_OLD_ICE_LARGE 28
#macro HG_VISUAL_EFFECT_OLD_ICE_SMALL 29

#macro HG_VISUAL_EFFECT_SPIRIT_FLAME_HIT 108
#macro HG_VISUAL_EFFECT_ORI_HIT_SMALL 109
#macro HG_VISUAL_EFFECT_ORI_HIT_LARGE 100
#macro HG_VISUAL_EFFECT_SEIN_HIT_SMALL 111
#macro HG_VISUAL_EFFECT_SEIN_HIT_LARGE 112
#macro HG_VISUAL_EFFECT_ORI_SWEETSPOT 113
#macro HG_VISUAL_EFFECT_LIGHT_GRENADE_EXPLOSION 115

#macro HG_VISUAL_EFFECT_POISON_SMALL 116
#macro HG_VISUAL_EFFECT_POISON_LARGE 117
#macro HG_VISUAL_EFFECT_POISON_SWEETSPOT 118
#macro HG_VISUAL_EFFECT_POISON_LARGE_2 119
#macro HG_VISUAL_EFFECT_POISON_LARGE_3 160
#macro HG_VISUAL_EFFECT_POISON_EXTRA_LARGE 120

#macro HG_VISUAL_EFFECT_STEAM_DIRECTIONAL 138
#macro HG_VISUAL_EFFECT_MISSILE_EXPLODE_SMALL 139
#macro HG_VISUAL_EFFECT_ROCKET_FIST_BURST 140
#macro HG_VISUAL_EFFECT_MISSILE_EXPLODE_MEDIUM 141
#macro HG_VISUAL_EFFECT_MINE_HIT 142
#macro HG_VISUAL_EFFECT_EXPLOSION_LARGE 143
#macro HG_VISUAL_EFFECT_STEAM_SMALL 144
#macro HG_VISUAL_EFFECT_MINE_COMBO_EXPLOSION 145

#macro HG_VISUAL_EFFECT_SHOVEL_EFFECT 306
#macro HG_VISUAL_EFFECT_BUZZSAW_DESTROY 151
#macro HG_VISUAL_EFFECT_GHOST_GLOVE_DISAPPEAR 152
#macro HG_VISUAL_EFFECT_MOBILE_GEAR_DESTROY 153
#macro HG_VISUAL_EFFECT_DIRT_BLOCK_DESTROY 154
#macro HG_VISUAL_EFFECT_COIN_CAPTURE 250
#macro HG_VISUAL_EFFECT_FLARE_ROD_HIT 251
#macro HG_VISUAL_EFFECT_SK_DSTRONG_HIT_SMALL 252
#macro HG_VISUAL_EFFECT_SK_DSTRONG_HIT_LARGE 253
#macro HG_VISUAL_EFFECT_WAR_HORN_HIT 254

#macro HG_VISUAL_EFFECT_PORTAL_SMALL 66
#macro HG_VISUAL_EFFECT_ABYSS_SMALL 67